version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: cybernetic-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cybernetic
      MYSQL_USER: amila
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
